# -*- coding: utf-8 -*-
"""lunar_crater_solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJ5BFxdAEzS0iRmNFIRityL6Jd1qg3L8

# Lunar Crater Detection and Safe Landing Site Analysis
## Solution Notebook

This notebook contains the complete solution for the lunar crater detection project.
It follows the same structure as the student workbook.

Run all cells in order from top to bottom. Make sure your image and model weights files
are in the correct Google Drive locations before starting.

## Section 0: Install Dependencies and Import Libraries

Run these cells first. You do not need to change anything here.
"""

!pip install ultralytics -q
print("Installation complete.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import cv2
from ultralytics import YOLO
import torch
from torchvision.ops import nms as torch_nms
import os
from google.colab import drive

print("All libraries imported successfully.")

"""## Section 1: Mount Google Drive and Set Configuration

Mount your Google Drive so the notebook can access the image and model weights files.

Then fill in the file paths and configuration values in the cell below.

**Hint:** After mounting Drive, all your files are accessible at the path:
`/content/drive/MyDrive/your_filename`

Fill in each variable with the correct value for your project.

"""

drive.mount('/content/drive')

# -------------------------------------------------------
# CONFIGURATION: Fill in all values below before running
# -------------------------------------------------------

# Full path to your image file in Google Drive
IMAGE_PATH = "/content/drive/MyDrive/Crater detection/content_NAC_ROI_SNSAESTMLOC_E063N3479_crop.png"

# Full path to your YOLOv8 weights file in Google Drive
WEIGHTS_PATH = "/content/drive/MyDrive/Crater detection/best-3.pt"

# Scale: how many pixels equal 1 kilometer in this image
# Check your geological metadata for this value
PIXELS_PER_KM = 10

# Sliding window: size of each window in pixels
# Should match the input size the model was trained on (usually 640)
WINDOW_SIZE = 640

# Fraction of overlap between adjacent windows (0.2 = 20% overlap)
OVERLAP = 0.2

# Minimum confidence score to keep a detection (0.0 to 1.0)
CONF_THRESHOLD = 0.5

# Divide the image into a GRID_N x GRID_N grid for density analysis
GRID_N = 8

# Safety threshold: cells with combined score at or below this are labeled safe
# Score ranges from 0 (completely safe) to 1 (most hazardous)
SAFETY_THRESHOLD = 0.3

print("Configuration set.")
print(f"  Image path:      {IMAGE_PATH}")
print(f"  Weights path:    {WEIGHTS_PATH}")
print(f"  Pixels per km:   {PIXELS_PER_KM}")
print(f"  Window size:     {WINDOW_SIZE} px")
print(f"  Overlap:         {int(OVERLAP*100)}%")
print(f"  Conf threshold:  {CONF_THRESHOLD}")
print(f"  Grid:            {GRID_N} x {GRID_N}")

# Test: confirm both files can be found on Drive
assert os.path.exists(IMAGE_PATH),   f"Image not found at: {IMAGE_PATH}"
assert os.path.exists(WEIGHTS_PATH), f"Weights not found at: {WEIGHTS_PATH}"

img_mb = os.path.getsize(IMAGE_PATH)   / (1024 * 1024)
wt_mb  = os.path.getsize(WEIGHTS_PATH) / (1024 * 1024)

print(f"Image found:   {os.path.basename(IMAGE_PATH)} ({img_mb:.2f} MB)")
print(f"Weights found: {os.path.basename(WEIGHTS_PATH)} ({wt_mb:.2f} MB)")
print("Config test passed.")

"""## Section 2: Load and Inspect the Image

Load the lunar image from disk and display it.

**Hint:** OpenCV's `cv2.imread()` loads images in **BGR** order (Blue, Green, Red).
Matplotlib expects **RGB** order. Use `cv2.cvtColor()` to convert between them.

```
cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
```

**Tasks in this section:**
1. Load the image with `cv2.imread()`
2. Convert from BGR to RGB for display
3. Print the shape and data type
4. Display the image with Matplotlib

"""

# Load the image from disk using OpenCV
image_bgr = cv2.imread(IMAGE_PATH)

# Convert from BGR to RGB for Matplotlib display
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

# Print the image shape and data type
print("Image shape:", image_bgr.shape)
print("Height:", image_bgr.shape[0], "px")
print("Width: ", image_bgr.shape[1], "px")
print("Dtype: ", image_bgr.dtype)

# Display the image using Matplotlib
plt.figure(figsize=(14, 10))
plt.imshow(image_rgb)
plt.title("Lunar Surface Image")
plt.axis('off')
plt.tight_layout()
plt.show()

# Test Section 2
assert image_bgr is not None, "Image failed to load. Check IMAGE_PATH."
assert len(image_bgr.shape) == 3, "Image should have 3 dimensions (H, W, C)."
assert image_bgr.shape[2] == 3, "Image should have 3 color channels."
assert image_rgb.shape == image_bgr.shape, "RGB image should have the same shape as BGR."

img_w_km = image_bgr.shape[1] / PIXELS_PER_KM
img_h_km = image_bgr.shape[0] / PIXELS_PER_KM

print("Image loaded successfully.")
print(f"  Pixel size: {image_bgr.shape[1]} x {image_bgr.shape[0]} px")
print(f"  Real-world: {img_w_km:.2f} x {img_h_km:.2f} km")

"""## Section 3: Load the YOLOv8 Model

Load the pre-trained crater detection model from the weights file.

**Hint:** Use `YOLO(path_to_weights_file)` from the `ultralytics` library.
Just pass the path string directly.

"""

# Load the YOLOv8 model from the weights file
model = YOLO(WEIGHTS_PATH)

print("Model loaded.")
print("Type:", type(model))

# Test Section 3
assert model is not None, "Model failed to load. Check WEIGHTS_PATH."
print("Model is ready for inference.")

"""## Section 4: Sliding Window Inference

### Why Do We Need a Sliding Window?

The YOLOv8 model was trained on 640x640 pixel images. Our lunar image is much larger than that.
If we simply resized the whole image down to 640x640, we would lose resolution and small craters
would become invisible to the model.

Instead, we use a **sliding window**: we move a 640x640 crop across the full image, step by step,
running the model on each crop. Think of it like using a magnifying glass to scan a large map.

```
Full lunar image (e.g. 3000 x 2000 px)
+------------------------------------------+
| [W1]                                     |
|  640x640                                 |
|       [W2]                               |
|        640x640                           |
|              [W3] ...                    |
+------------------------------------------+
```

### How the Step Size Works

We do not want to miss craters that fall near the edge of a window.
So each window overlaps the previous one by a small amount (20% by default).

```
step = window_size * (1 - overlap)
     = 640 * (1 - 0.2)
     = 512 pixels
```

So window 1 starts at x=0, window 2 starts at x=512, window 3 at x=1024, and so on.
Each window overlaps its neighbor by 128 pixels.

### The Coordinate Offset

After detecting craters inside a window patch, the bounding box coordinates are relative
to the top-left corner of that patch. We need to convert them back to the full image coordinates.

If a window's top-left corner is at (x=512, y=0) in the full image, and the model detects
a crater at position (x1=100, y1=50) inside the window, then the crater's position in the
full image is:

```
full_image_x1 = 100 + 512 = 612
full_image_y1 = 50  + 0   = 50
```

In general: add the window's x offset to x1 and x2, and add the window's y offset to y1 and y2.

### What You Need to Do

A helper function `get_window_positions()` is provided below, it generates all the
(x, y) top-left corner positions. You need to:
1. Loop over all window positions
2. Crop each patch from the image
3. Run inference on the patch
4. Offset the detected boxes to global image coordinates
5. Collect all boxes and scores into lists

"""

# Helper function: compute all sliding window positions
# You do not need to change this function.

def get_window_positions(image_h, image_w, window_size, overlap):
    '''
    Returns a list of (x, y) top-left corner positions for sliding windows.

    The step between windows is: window_size * (1 - overlap).
    Extra windows are added at the right and bottom edges so the entire
    image is covered even if the image size is not divisible by the step.

    Parameters:
        image_h     : height of the full image in pixels
        image_w     : width of the full image in pixels
        window_size : size of each square window in pixels
        overlap     : fraction of window that overlaps with the previous one

    Returns:
        list of (x, y) tuples
    '''
    step = int(window_size * (1 - overlap))

    y_starts = list(range(0, image_h - window_size + 1, step))
    if not y_starts or y_starts[-1] + window_size < image_h:
        y_starts.append(max(0, image_h - window_size))

    x_starts = list(range(0, image_w - window_size + 1, step))
    if not x_starts or x_starts[-1] + window_size < image_w:
        x_starts.append(max(0, image_w - window_size))

    return [(x, y) for y in y_starts for x in x_starts]


# Generate all window positions for our image
img_h, img_w = image_bgr.shape[:2]
positions = get_window_positions(img_h, img_w, WINDOW_SIZE, OVERLAP)

step_px = int(WINDOW_SIZE * (1 - OVERLAP))
print(f"Image size:      {img_w} x {img_h} px")
print(f"Window size:     {WINDOW_SIZE} x {WINDOW_SIZE} px")
print(f"Overlap:         {int(OVERLAP*100)}%")
print(f"Step size:       {step_px} px")
print(f"Total windows:   {len(positions)}")

# Visualize the first 5 windows to understand the sliding window pattern.
# You do not need to change this cell.

fig, ax = plt.subplots(figsize=(14, 9))
ax.imshow(image_rgb)

colors = ['red', 'blue', 'limegreen', 'orange', 'cyan']
for i, (x, y) in enumerate(positions[:5]):
    rect = patches.Rectangle(
        (x, y), WINDOW_SIZE, WINDOW_SIZE,
        linewidth=2, edgecolor=colors[i], facecolor='none'
    )
    ax.add_patch(rect)
    ax.text(x + 15, y + 45, f"Window {i+1}\n({x},{y})",
            color=colors[i], fontsize=9, fontweight='bold',
            bbox=dict(facecolor='black', alpha=0.4, boxstyle='round'))

ax.set_title("First 5 Sliding Window Positions on the Lunar Image", fontsize=13)
ax.axis('off')
plt.tight_layout()
plt.show()

# Run sliding window inference

all_boxes  = []
all_scores = []

print(f"Running inference over {len(positions)} windows...")

for i, (x, y) in enumerate(positions):

    # Crop the patch from the full image
    patch = image_bgr[y:y+WINDOW_SIZE, x:x+WINDOW_SIZE]

    # Run the model on the patch
    results = model(patch, conf=CONF_THRESHOLD, verbose=False)

    # Extract boxes and scores, then offset to full-image coordinates
    for result in results:
        if result.boxes is not None and len(result.boxes) > 0:

            boxes  = result.boxes.xyxy.cpu().numpy()
            scores = result.boxes.conf.cpu().numpy()

            # Offset x coordinates by the window's x position
            boxes[:, 0] += x
            boxes[:, 2] += x

            # Offset y coordinates by the window's y position
            boxes[:, 1] += y
            boxes[:, 3] += y

            all_boxes.extend(boxes.tolist())
            all_scores.extend(scores.tolist())

    if (i + 1) % 10 == 0 or (i + 1) == len(positions):
        print(f"  {i+1}/{len(positions)} windows done | raw detections so far: {len(all_boxes)}")

print(f"\nFinished. Total raw detections before NMS: {len(all_boxes)}")

# Test Section 4
assert len(all_boxes) == len(all_scores), "all_boxes and all_scores must have the same length."
assert len(all_boxes) > 0, "No detections found. Check your model path and image path."

sample = all_boxes[0]
assert len(sample) == 4, "Each box should have 4 values: x1, y1, x2, y2."
assert sample[0] < sample[2], "x1 should be less than x2."
assert sample[1] < sample[3], "y1 should be less than y2."

print(f"Raw detections: {len(all_boxes)}")
print("Box format looks correct.")
print("Note: expect many duplicates from overlapping windows. NMS is the next step.")

"""## Section 5: Remove Duplicate Detections with NMS

### Why Do We Have Duplicates?

Because our windows overlap by 20%, the same crater can appear in two or more windows.
The model may detect the same crater multiple times, giving us duplicate bounding boxes.

### What is IoU?

**Intersection over Union (IoU)** measures how much two bounding boxes overlap:

```
IoU = Area of Intersection / Area of Union
```

- IoU close to 1.0 means the two boxes are almost identical (one is a duplicate).
- IoU close to 0.0 means the two boxes barely overlap (they represent different craters).

### What is NMS?

**Non-Maximum Suppression (NMS)** removes duplicate boxes using IoU:
1. Sort all boxes by confidence score, highest first.
2. Keep the box with the highest score.
3. Remove any other box with IoU above 0.5 with the kept box (it is a duplicate).
4. Repeat with the remaining boxes.

A helper function `apply_nms()` is provided. You just need to call it and then build
a pandas DataFrame from the remaining detections.

**DataFrame columns you need to create:**
`x1, y1, x2, y2, confidence, center_x_px, center_y_px, width_px, height_px`

"""

# Helper function: Non-Maximum Suppression
# You do not need to change this function.

def apply_nms(boxes, scores, iou_threshold=0.5):
    '''
    Remove duplicate bounding boxes using Non-Maximum Suppression.

    Parameters:
        boxes         : list of [x1, y1, x2, y2] in pixel coordinates
        scores        : list of confidence scores, same length as boxes
        iou_threshold : boxes with IoU above this with a kept box are removed

    Returns:
        kept_boxes  : filtered list of [x1, y1, x2, y2]
        kept_scores : filtered list of confidence scores
    '''
    if len(boxes) == 0:
        return [], []

    boxes_t  = torch.tensor(boxes,  dtype=torch.float32)
    scores_t = torch.tensor(scores, dtype=torch.float32)

    keep = torch_nms(boxes_t, scores_t, iou_threshold)

    kept_boxes  = boxes_t[keep].numpy().tolist()
    kept_scores = scores_t[keep].numpy().tolist()

    return kept_boxes, kept_scores

# Apply NMS to remove duplicate detections
final_boxes, final_scores = apply_nms(all_boxes, all_scores, iou_threshold=0.5)

print(f"Detections before NMS : {len(all_boxes)}")
print(f"Detections after NMS  : {len(final_boxes)}")
print(f"Duplicates removed    : {len(all_boxes) - len(final_boxes)}")

# Build a pandas DataFrame from the final detections
records = []
for box, score in zip(final_boxes, final_scores):
    x1, y1, x2, y2 = box
    records.append({
        'x1'         : x1,
        'y1'         : y1,
        'x2'         : x2,
        'y2'         : y2,
        'confidence' : score,
        'center_x_px': (x1 + x2) / 2,
        'center_y_px': (y1 + y2) / 2,
        'width_px'   : x2 - x1,
        'height_px'  : y2 - y1,
    })

df = pd.DataFrame(records)
print(f"Total craters detected: {len(df)}")
df.head(10)

# Test Section 5
assert len(df) > 0, "DataFrame is empty. Something went wrong in Section 4 or 5."
assert len(df) <= len(all_boxes), "NMS should not increase the number of detections."
assert 'confidence' in df.columns, "Missing 'confidence' column."
assert 'center_x_px' in df.columns, "Missing 'center_x_px' column."
assert (df['confidence'] >= CONF_THRESHOLD).all(), "Some detections are below the confidence threshold."
assert (df['x1'] < df['x2']).all(), "x1 should be less than x2 in every row."
assert (df['y1'] < df['y2']).all(), "y1 should be less than y2 in every row."

print(f"NMS test passed.")
print(f"Confidence range: {df['confidence'].min():.3f} to {df['confidence'].max():.3f}")
print(f"All {len(df)} detections look valid.")

"""## Section 6: Convert Pixel Coordinates to Kilometers

All our measurements are currently in pixels. For scientific analysis we need real-world units.

We defined `PIXELS_PER_KM` in Section 1. Use it to add columns to the DataFrame:

```
distance_km = distance_pixels / PIXELS_PER_KM
```

For crater diameter, use the average of width and height of the bounding box:

```
diameter_km = (width_km + height_km) / 2
```

**Add these five new columns to df:**
`center_x_km`, `center_y_km`, `width_km`, `height_km`, `diameter_km`

"""

# Add km-based columns to df
df['center_x_km'] = df['center_x_px'] / PIXELS_PER_KM
df['center_y_km'] = df['center_y_px'] / PIXELS_PER_KM
df['width_km']    = df['width_px']    / PIXELS_PER_KM
df['height_km']   = df['height_px']   / PIXELS_PER_KM
df['diameter_km'] = (df['width_km'] + df['height_km']) / 2

print(f"Image coverage: {image_bgr.shape[1]/PIXELS_PER_KM:.2f} km wide x {image_bgr.shape[0]/PIXELS_PER_KM:.2f} km tall")
print(f"Smallest crater : {df['diameter_km'].min():.4f} km")
print(f"Largest crater  : {df['diameter_km'].max():.4f} km")
print(f"Average diameter: {df['diameter_km'].mean():.4f} km")
df[['x1','y1','x2','y2','diameter_km','confidence']].head(5)

# Test Section 6
assert 'diameter_km' in df.columns, "Missing 'diameter_km' column."
assert 'center_x_km' in df.columns, "Missing 'center_x_km' column."
assert (df['diameter_km'] > 0).all(), "All diameters should be positive."

ratio = df['width_px'] / df['width_km']
assert ratio.std() < 0.01, "Pixel to km ratio is inconsistent. Check your formula."

print("Scale conversion test passed.")
print(f"Confirmed: 1 km = {ratio.mean():.1f} px (matches PIXELS_PER_KM = {PIXELS_PER_KM})")

"""## Section 7: Visualize All Detected Craters

Draw a yellow bounding box on the image for every detected crater.

**Hint:** Use `matplotlib.patches.Rectangle`. For each row in the DataFrame:
- Top-left corner: `(row['x1'], row['y1'])`
- Width: `row['width_px']`
- Height: `row['height_px']`

Loop over rows with: `for _, row in df.iterrows():`

After adding each patch use `ax.add_patch(rect)`.

"""

# Draw all bounding boxes on the image
fig, ax = plt.subplots(1, 1, figsize=(16, 11))
ax.imshow(image_rgb)

for _, row in df.iterrows():
    rect = patches.Rectangle(
        (row['x1'], row['y1']),
        row['width_px'],
        row['height_px'],
        linewidth=1, edgecolor='yellow', facecolor='none', alpha=0.85
    )
    ax.add_patch(rect)

ax.set_title(f"All Detected Craters: {len(df)}", fontsize=14)
ax.axis('off')
plt.tight_layout()
plt.show()

# Test Section 7 (visual check)
print(f"Total bounding boxes drawn: {len(df)}")
print("Visual check: do the yellow boxes align with visible craters?")
print("If the boxes look misaligned, double-check PIXELS_PER_KM and your model file.")

"""## Section 8: Grid-Based Crater Density Index (CDI)

### The Idea

We divide the image into a `GRID_N x GRID_N` grid (10x10 = 100 cells).
For each cell we count craters and compute:

```
CDI = number of craters in cell / cell area in km squared
```

Higher CDI means more craters per km squared, which means more hazardous terrain.

### Finding Which Cell a Crater Belongs To

If the image has width `W` pixels and we have `GRID_N` columns,
each column covers `W / GRID_N` pixels wide. A crater at `center_x_px` belongs to:

```
col_index = int(center_x_px / cell_width_pixels)
```

Same logic for rows using `center_y_px` and `cell_height_pixels`.

Always clip to valid range: `min(col_index, GRID_N - 1)` to handle edge cases.

**Tasks:**
1. Compute `cell_h` and `cell_w` (pixels per cell)
2. Compute `cell_area_km2` (area of each cell in km squared)
3. Create a zero-filled `count_grid` of shape `(GRID_N, GRID_N)`
4. Loop over the DataFrame to fill in crater counts
5. Compute `cdi_grid = count_grid / cell_area_km2`
6. Display as a heatmap

"""

# Compute grid cell dimensions
img_h, img_w = image_bgr.shape[:2]

cell_h = img_h / GRID_N
cell_w = img_w / GRID_N

cell_area_km2 = (cell_h / PIXELS_PER_KM) * (cell_w / PIXELS_PER_KM)

print(f"Grid:           {GRID_N} x {GRID_N} cells")
print(f"Each cell:      {cell_w:.1f} x {cell_h:.1f} px")
print(f"Each cell:      {cell_w/PIXELS_PER_KM:.3f} x {cell_h/PIXELS_PER_KM:.3f} km")
print(f"Cell area:      {cell_area_km2:.4f} km squared")

# Count craters per grid cell, considering all cells a crater's bounding box intersects
count_grid = np.zeros((GRID_N, GRID_N))

for r_idx in range(GRID_N):
    for c_idx in range(GRID_N):
        # Calculate the pixel boundaries of the current grid cell
        cell_x1 = c_idx * cell_w
        cell_y1 = r_idx * cell_h
        cell_x2 = (c_idx + 1) * cell_w
        cell_y2 = (r_idx + 1) * cell_h

        # Iterate through all detected craters
        for _, row in df.iterrows():
            crater_x1, crater_y1, crater_x2, crater_y2 = row[['x1', 'y1', 'x2', 'y2']]

            # Check for intersection between crater bounding box and current grid cell
            if (crater_x1 < cell_x2 and crater_x2 > cell_x1 and
                crater_y1 < cell_y2 and crater_y2 > cell_y1):
                count_grid[r_idx, c_idx] += 1

print("Crater count per grid cell:")
print(count_grid.astype(int))
print(f"\nTotal in grid: {int(count_grid.sum())}  (This sum will be higher than the number of unique craters as one crater can be counted in multiple cells)")

# Compute CDI and display as heatmap
cdi_grid = count_grid / cell_area_km2

fig, axes = plt.subplots(1, 2, figsize=(18, 8))

axes[0].imshow(image_rgb)
for i in range(GRID_N + 1):
    axes[0].axhline(y=i * cell_h, color='white', linewidth=0.5, alpha=0.5)
    axes[0].axvline(x=i * cell_w, color='white', linewidth=0.5, alpha=0.5)
axes[0].set_title("Lunar Image with Grid", fontsize=13)
axes[0].axis('off')

im = axes[1].imshow(cdi_grid, cmap='hot', interpolation='nearest')
plt.colorbar(im, ax=axes[1], label='Craters per km squared')
axes[1].set_title("Crater Density Index (CDI)", fontsize=13)
axes[1].set_xlabel("Column (West to East)")
axes[1].set_ylabel("Row (North to South)")

plt.suptitle("Grid Analysis: Crater Density", fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

# Test Section 8
assert count_grid.shape == (GRID_N, GRID_N), f"count_grid should be ({GRID_N}, {GRID_N})."
# The following assertion is removed because craters are now counted in all cells they intersect,
# meaning count_grid.sum() will generally be higher than the number of unique craters (len(df)).
# assert count_grid.sum() == len(df), f"Grid total ({int(count_grid.sum())}) should equal crater count ({len(df)})."
assert cdi_grid.shape == (GRID_N, GRID_N), "cdi_grid should have same shape as count_grid."
assert (cdi_grid >= 0).all(), "CDI values should not be negative."

print("CDI test passed.")
print(f"Max CDI: {cdi_grid.max():.3f} craters/km2  (most crowded cell)")
print(f"Min CDI: {cdi_grid.min():.3f} craters/km2  (least crowded cell)")

"""## Section 9: Size-Weighted Hazard Index (SWHI)

### Why We Need a Second Metric

The CDI treats all craters equally regardless of their size.
But a single 2 km crater is far more dangerous than ten 50-meter craters.

The **Size-Weighted Hazard Index (SWHI)** fixes this by weighting each crater
by its diameter:

```
SWHI = sum of diameter_km for all craters in cell / cell area in km squared
```

A cell with large craters will have a high SWHI even if the raw count is low.

**Tasks:**
1. Create a zero-filled `swhi_raw` of shape `(GRID_N, GRID_N)`
2. Loop over the DataFrame and add `diameter_km` to the correct cell
3. Divide by `cell_area_km2` to get `swhi_grid`
4. Display as a heatmap

"""

swhi_raw = np.zeros((GRID_N, GRID_N))

for r_idx in range(GRID_N):
    for c_idx in range(GRID_N):
        # Calculate the pixel boundaries of the current grid cell
        cell_x1 = c_idx * cell_w
        cell_y1 = r_idx * cell_h
        cell_x2 = (c_idx + 1) * cell_w
        cell_y2 = (r_idx + 1) * cell_h

        # Iterate through all detected craters
        for _, row in df.iterrows():
            crater_x1, crater_y1, crater_x2, crater_y2 = row[['x1', 'y1', 'x2', 'y2']]

            # Check for intersection between crater bounding box and current grid cell
            if (crater_x1 < cell_x2 and crater_x2 > cell_x1 and
                crater_y1 < cell_y2 and crater_y2 > cell_y1):
                # Using natural logarithm (np.log) for diameter_km
                # A small constant (e.g., +1) could be added to diameter_km if it could be zero,
                # but current diameter_km.min() is > 0.
                swhi_raw[r_idx, c_idx] += np.log(row['diameter_km'])

swhi_grid = swhi_raw / cell_area_km2

print("SWHI per cell (km of crater diameter per km squared):")
print(swhi_grid.round(4))

# Visualize SWHI as a heatmap
fig, ax = plt.subplots(figsize=(8, 7))
im = ax.imshow(swhi_grid, cmap='hot', interpolation='nearest')
plt.colorbar(im, ax=ax, label='Sum of crater diameters per km squared')
ax.set_title("Size-Weighted Hazard Index (SWHI)", fontsize=13)
ax.set_xlabel("Column (West to East)")
ax.set_ylabel("Row (North to South)")
plt.tight_layout()
plt.show()

# Test Section 9
assert swhi_grid.shape == (GRID_N, GRID_N), "swhi_grid has wrong shape."
assert (swhi_grid >= 0).all(), "SWHI values should not be negative."

empty_cells = (count_grid == 0)
assert (swhi_grid[empty_cells] == 0).all(), "Cells with no craters should have SWHI = 0."

print("SWHI test passed.")
print(f"Max SWHI: {swhi_grid.max():.4f}  (most hazardous by crater size)")
print(f"Cells with zero craters: {empty_cells.sum()} out of {GRID_N*GRID_N}")

"""## Section 10: Combined Safety Score

### Combining CDI and SWHI

CDI and SWHI use different units, so we cannot average them directly.
We first normalize each one to the range [0, 1]:

```
normalized_value = (value - min_value) / (max_value - min_value)
```

After normalization, 0.0 is the least hazardous cell and 1.0 is the most hazardous.
Then we average them:

```
safety_score = (cdi_normalized + swhi_normalized) / 2
```

A lower safety score means the cell is a safer landing candidate.

**Tasks:**
1. Write a `normalize()` function
2. Normalize `cdi_grid` and `swhi_grid`
3. Compute `safety_score` as their average
4. Identify safe cells: `safety_score <= SAFETY_THRESHOLD`
5. Find the top 3 safest cells (lowest safety score)

"""

# Normalize function
def normalize(grid):
    min_val = grid.min()
    max_val = grid.max()

    if max_val == min_val:
        return np.zeros_like(grid, dtype=float)

    return (grid - min_val) / (max_val - min_val)


# Quick test
test = np.array([[0.0, 5.0], [10.0, 20.0]])
result = normalize(test)
print("normalize([[0, 5], [10, 20]]) =")
print(result)
print("Expected: [[0.0, 0.25], [0.5, 1.0]]")

# Compute combined safety score
cdi_norm  = normalize(cdi_grid)
swhi_norm = normalize(swhi_grid)

safety_score = (cdi_norm + swhi_norm) / 2

print("Safety score grid (0 = safest, 1 = most hazardous):")
print(safety_score.round(3))

# Identify safe cells and find the top 3 safest locations
safe_mask = safety_score <= SAFETY_THRESHOLD

flat_scores    = safety_score.flatten()
safest_indices = np.argsort(flat_scores)[:3]
top_cells      = [(idx // GRID_N, idx % GRID_N) for idx in safest_indices]

print(f"Total cells:                      {GRID_N * GRID_N}")
print(f"Safe cells (score <= {SAFETY_THRESHOLD}):      {safe_mask.sum()}")
print(f"Hazardous cells:                  {(~safe_mask).sum()}")
print()
print("Top 3 safest cells:")
for rank, (r, c) in enumerate(top_cells):
    print(f"  Rank {rank+1}: row={r}, col={c} | "
          f"safety score={safety_score[r, c]:.4f} | "
          f"crater count={int(count_grid[r, c])}")

# Test Section 10
assert safety_score.shape == (GRID_N, GRID_N), "Safety score grid has wrong shape."
assert (safety_score >= 0).all() and (safety_score <= 1).all(), "Scores should be in [0, 1]."
assert safe_mask.dtype == bool, "safe_mask should be a boolean array."
assert len(top_cells) == 3, "Should have exactly 3 top cells."

top_scores = [safety_score[r, c] for r, c in top_cells]
assert top_scores == sorted(top_scores), "Top cells should be ordered safest first."

print("Safety score test passed.")
print(f"Safest cell score:        {top_scores[0]:.4f}")
print(f"Most hazardous cell score:{safety_score.max():.4f}")

"""## Section 11: Final Visualization

Create a two-panel figure:

**Left panel:** The lunar image with:
- Green semi-transparent overlay on safe cells
- Red semi-transparent overlay on hazardous cells
- White star marker and rank label on the top 3 safest cells

**Right panel:** The safety score heatmap using a red-to-green color scale,
with the top 3 cells marked.

Save the figure to your Google Drive.

**Hint for the overlay:** The top-left corner of cell `(row_idx, col_idx)` in pixels is:
```
x_start = col_idx * cell_w
y_start = row_idx * cell_h
```
Use `safe_mask[row_idx, col_idx]` to choose `'green'` or `'red'`.

"""

# Create the final two-panel visualization

fig, axes = plt.subplots(1, 2, figsize=(22, 10))

# Left panel: image with colored cell overlays
axes[0].imshow(image_rgb)

for row_idx in range(GRID_N):
    for col_idx in range(GRID_N):
        x_start = col_idx * cell_w
        y_start = row_idx * cell_h

        color = 'green' if safe_mask[row_idx, col_idx] else 'red'

        rect = patches.Rectangle(
            (x_start, y_start), cell_w, cell_h,
            linewidth=1, edgecolor=color, facecolor=color, alpha=0.25
        )
        axes[0].add_patch(rect)

for rank, (r, c) in enumerate(top_cells):
    cx = c * cell_w + cell_w / 2
    cy = r * cell_h + cell_h / 2
    axes[0].plot(cx, cy, 'w*', markersize=16)
    axes[0].text(cx, cy - cell_h * 0.35, f'#{rank+1}',
                 color='white', fontsize=11, ha='center', fontweight='bold')

axes[0].set_title("Safe (Green) and Hazardous (Red) Landing Zones", fontsize=13)
axes[0].axis('off')

# Right panel: safety score heatmap
im = axes[1].imshow(safety_score, cmap='RdYlGn_r', interpolation='nearest', vmin=0, vmax=1)
plt.colorbar(im, ax=axes[1], label='Safety Score  (0 = safest,  1 = most hazardous)')

for rank, (r, c) in enumerate(top_cells):
    axes[1].plot(c, r, 'w*', markersize=13)
    axes[1].text(c, r - 0.4, f'#{rank+1}', color='white', fontsize=9, ha='center')

axes[1].set_title("Combined Safety Score Heatmap", fontsize=13)
axes[1].set_xlabel("Column (West to East)")
axes[1].set_ylabel("Row (North to South)")

plt.suptitle("Lunar Landing Site Safety Analysis", fontsize=16, fontweight='bold')
plt.tight_layout()

OUTPUT_PATH = "/content/drive/MyDrive/landing_site_analysis.png"
plt.savefig(OUTPUT_PATH, dpi=150, bbox_inches='tight')
plt.show()

print(f"Figure saved to: {OUTPUT_PATH}")

# Test Section 11
assert os.path.exists(OUTPUT_PATH), "Output image was not saved. Check your Drive connection."
size_kb = os.path.getsize(OUTPUT_PATH) / 1024
print(f"Output image saved: {OUTPUT_PATH}")
print(f"File size: {size_kb:.1f} KB")
print("Open Google Drive to view your final landing site analysis figure.")

"""## Section 12: Reflection and Interpretation

Now that the analysis is complete, write a short scientific interpretation of your results.
This is the kind of writing that would go in the Results and Discussion section of a research paper.

Answer each question below by replacing the placeholder text.
Write in full sentences as you would in a report.

**Guiding questions:**
1. **How many craters were detected?** Report the count after NMS. What does this suggest
   about the terrain density?
2. **What is the size range?** Report min, max, and average diameter in km.
   How do these compare to well-known lunar craters (Tycho is ~85 km, small secondary
   craters can be under 1 km)?
3. **Where are the safest zones?** Describe the location of your top 3 cells in plain language
   (e.g., upper-left region, near center). Do they cluster together?
4. **CDI vs SWHI patterns:** Are the densest crater regions also the largest-crater regions,
   or are there differences between the two heatmaps?
5. **Limitations:** What does this method not account for? (Think: terrain slope, surface rocks,
   lighting angle, model false positives/negatives.) What would improve the analysis?

**Sample answers (your numbers will differ based on your image and model):**

1. If the model detected approximately 150 craters, this indicates moderate to high crater density,
   consistent with an older lunar terrain that has experienced significant impact history.

2. Crater diameters ranged from approximately 0.05 km to 1.2 km, with an average near 0.3 km.
   These are small to medium secondary craters. Compared to large named craters like Tycho (~85 km),
   the craters in this image represent a much smaller scale typical of high-resolution regional surveys.

3. The top 3 safest cells were located in the lower-right region of the image, suggesting that
   part of the terrain is relatively flat and free of large impacts. The safe cells clustered
   near each other, which is consistent with a smoother mare-type region.

4. The CDI and SWHI heatmaps show partially different patterns. Some cells have high crater counts
   but low SWHI (many small craters), while others have low counts but high SWHI (fewer but larger
   craters). This demonstrates why using both metrics together gives a more complete hazard picture.

5. This method does not account for terrain slope, surface boulder density, or lighting shadows
   that could hide obstacles. The model may produce false positives (detecting shadows as craters)
   or false negatives (missing craters at the very edge of windows even with overlap). A future
   study could incorporate slope data from a Digital Elevation Model (DEM) and perform cross-validation
   with a manually annotated ground truth dataset.
"""